name: on-push

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-component-types: ${{ steps.components-changed.outputs.changed-component-types }}
      changed-components-by-type: ${{ steps.components-changed.outputs.changed-components-by-type }}
    steps:
      -
        uses: actions/checkout@v6
      -
        name: Detect changed components
        id: components-changed
        uses: slingshot-pipelines/action-components-changed@v1

  release-library:
    needs: detect-changes
    if: ${{ contains(needs.detect-changes.outputs.changed-component-types, '"library"') }}
    uses: slingshot-pipelines/workflows/.github/workflows/release-library.yml@release-library/v1
    strategy:
      matrix:
        COMPONENT: ${{ fromJSON(needs.detect-changes.outputs.changed-components-by-type).library }}
    with:
      COMPONENT: ${{ matrix.COMPONENT }}
    secrets: inherit

  goreleaser:
    needs:
      - detect-changes
      - release-library
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      -
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      -
        name: Fetch app token
        id: brewer-app-token
        uses: actions/create-github-app-token@v3
        with:
          owner: ${{ github.repository_owner }}
          client-id: ${{ secrets.BREWER_APP_CLIENT_ID }}
          private-key: ${{ secrets.BREWER_APP_PRIVATE_KEY }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ github.token }}
          HOMEBREW_TOKEN: ${{ steps.brewer-app-token.outputs.token }}
